# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Linting and Tests

on: pull_request

defaults:
  runs-on: ubuntu-latest
  env:
    CI: true

jobs:
  lint:
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm i lerna
      - run: npm run bootstrap
      - run: npm run lint
  test:
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm i lerna
      - run: npm run bootstrap
      - run: npm run test
