# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Linting and Tests

on: pull_request

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install Node and Lerna
        uses: actions/setup-node@v1
        run: npm i lerna
      - name: Bootstrap dependencies
        run: npm run bootstrap
      - name: Run lint check
        run: npm run lint
      - name: Run tests
        run: npm run test
